import React, { useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { ConvexHeroWorkbench } from './ConvexHeroWorkbench';

export const ConvexHero: React.FC = () => {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState(0);

  const handleCopy = () => {
    navigator.clipboard.writeText('npx create convex');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const tabs = [
    {
      title: 'Everything is code',
      description:
        'From database schemas to queries, from crons to HTTP actions, express all part of your backend in pure TypeScript. Your backend runs right next to your database, so everything is fast and type-safe. Frontend is generated by AI with exceptional accuracy.',
    },
    {
      title: 'Always in sync',
      description:
        'Convex automatically tracks your queries and keeps clients in real-time sync with database state over WebSockets without manual subscriptions or polling.',
    },
    {
      title: 'Backend built-ins',
      description:
        'Vector search, scheduled functions, file storage, auth, and ACID transactions are built straight into the platform with zero external glue code.',
    },
  ];

  return (
    <section className="w-full bg-[#f6f6f6] py-12 lg:py-16 px-6 select-none border-b border-[#e5e5e5]">
      <div className="max-w-[1240px] mx-auto grid grid-cols-1 lg:grid-cols-12 gap-10 items-start">
        
        {/* Left Column (5 cols): Headline, CTAs, Vertical Tabs */}
        <div className="lg:col-span-5 flex flex-col gap-8">
          <div className="flex flex-col gap-4">
            <h1 className="text-4xl sm:text-5xl lg:text-[54px] font-bold text-[#141414] tracking-[-0.05em] leading-[1.05]">
              The backend platform that keeps your app in sync
            </h1>
          </div>

          {/* Action CTAs */}
          <div className="flex flex-wrap items-center gap-3">
            <button
              type="button"
              className="inline-flex items-center justify-center px-5 py-2.5 rounded-lg bg-[#ffffff] hover:bg-[#eaeaea] border border-[#e5e5e5] text-[#141414] font-medium text-sm transition-colors cursor-pointer"
            >
              Start building
            </button>

            {/* Command Snippet Card */}
            <button
              type="button"
              onClick={handleCopy}
              className="flex items-center gap-2.5 px-4 py-2.5 rounded-lg bg-[#292929] hover:bg-[#333333] border border-[#38383a] font-mono text-xs text-white transition-colors cursor-pointer group"
              title="Copy npx create convex command"
            >
              <span className="text-[#6d6d70] select-none">&gt;</span>
              <span className="text-white font-medium">npx create convex</span>
              {copied ? (
                <Check className="w-3.5 h-3.5 text-[#7bd88f] ml-1" />
              ) : (
                <Copy className="w-3.5 h-3.5 text-[#a9a9ac] group-hover:text-white ml-1 transition-colors" />
              )}
            </button>
          </div>

          {/* Vertical Feature Tabs (Convex Signature Accordion) */}
          <div className="flex flex-col border-t border-[#e5e5e5] pt-6 gap-2">
            {tabs.map((tab, idx) => {
              const isActive = activeTab === idx;
              return (
                <div
                  key={tab.title}
                  onClick={() => setActiveTab(idx)}
                  className={`p-4 rounded-xl cursor-pointer transition-all border ${
                    isActive
                      ? 'bg-[#ffffff] border-[#e5e5e5]'
                      : 'border-transparent hover:bg-[#eeeeee]'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span
                      className={`text-base font-bold tracking-tight ${
                        isActive ? 'text-[#141414]' : 'text-[#4f4f52]'
                      }`}
                    >
                      {tab.title}
                    </span>
                  </div>
                  {isActive && (
                    <p className="mt-2 text-sm text-[#4f4f52] leading-relaxed font-normal">
                      {tab.description}
                    </p>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Column (7 cols): The Large Dark Workbench */}
        <div className="lg:col-span-7 flex flex-col">
          <ConvexHeroWorkbench />
        </div>

      </div>
    </section>
  );
};
