import React, { useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { ConvexHeroNavbar } from './ConvexHeroNavbar';
import { ConvexHeroWorkbench } from './ConvexHeroWorkbench';

export const ConvexHero: React.FC = () => {
  const [copied, setCopied] = useState(false);
  const [activeStep, setActiveStep] = useState(0);

  const handleCopy = () => {
    navigator.clipboard.writeText('npm create convex');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const steps = [
    {
      title: 'Everything is code',
      desc: 'From database schemas to queries, from auth to APIs, express every part of your backend in pure TypeScript. Your backend code lives next to your app code, is typechecked and autocompleted, and is generated by AI with exceptional accuracy.',
      index: '01',
    },
    {
      title: 'Always in sync',
      desc: 'Convex automatically tracks your queries and keeps clients in real-time sync with database state over WebSockets without manual subscriptions or polling.',
      index: '02',
    },
    {
      title: 'Backend built-ins',
      desc: 'Vector search, scheduled functions, file storage, auth, and ACID transactions are built straight into the platform with zero external glue code.',
      index: '03',
    },
  ];

  return (
    <section className="w-full px-3 sm:px-6 pt-4 pb-12 select-none">
      {/* Outer Giant Dark Hero Card */}
      <div className="max-w-[1460px] mx-auto bg-[#2b2e26] border border-[#3c4134] rounded-[28px] p-6 sm:p-8 lg:p-10 flex flex-col">
        {/* Top Navbar inside Hero Card */}
        <ConvexHeroNavbar />

        {/* Hero Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-10 items-start">
          {/* Left Column (5 cols) */}
          <div className="lg:col-span-5 flex flex-col justify-between pt-2">
            <div>
              {/* Display Headline */}
              <h1 className="text-4xl sm:text-5xl xl:text-[54px] font-bold text-white tracking-[-0.04em] leading-[1.05]">
                The backend <br />
                platform that keeps <br />
                your app in sync
              </h1>

              {/* CTAs */}
              <div className="flex flex-wrap items-center gap-3 mt-7 mb-10">
                <button
                  type="button"
                  className="px-6 py-2.5 rounded-full bg-white hover:bg-neutral-100 text-[#191b16] font-semibold text-sm transition-colors cursor-pointer"
                >
                  Start building
                </button>

                <button
                  type="button"
                  onClick={handleCopy}
                  className="flex items-center gap-2.5 px-4 py-2.5 rounded-xl bg-[#373c2f] hover:bg-[#414738] border border-[#484e3e] font-mono text-xs text-[#d6dad0] transition-colors cursor-pointer group"
                  title="Copy npm create convex command"
                >
                  <span className="text-[#8e9385] select-none">&gt;</span>
                  <span>npm create convex</span>
                  {copied ? (
                    <Check className="w-3.5 h-3.5 text-[#7bd88f] ml-1" />
                  ) : (
                    <Copy className="w-3.5 h-3.5 text-[#8e9385] group-hover:text-white ml-1 transition-colors" />
                  )}
                </button>
              </div>
            </div>

            {/* Vertical 3-Step Accordion */}
            <div className="border-t border-[#3c4134] pt-4 flex flex-col">
              {steps.map((step, idx) => {
                const isActive = activeStep === idx;
                return (
                  <div key={step.title} className="border-b border-[#3c4134] last:border-b-0 py-3.5">
                    <button
                      type="button"
                      onClick={() => setActiveStep(idx)}
                      className={`w-full text-left font-semibold text-base transition-colors flex items-center justify-between cursor-pointer ${
                        isActive ? 'text-white' : 'text-[#8e9385] hover:text-[#cfd3c7]'
                      }`}
                    >
                      <span>{step.title}</span>
                    </button>
                    {isActive && (
                      <div className="mt-2.5 pr-4">
                        <p className="text-xs sm:text-[13px] text-[#9ba092] leading-relaxed">
                          {step.desc}
                        </p>
                        <div className="mt-3 text-[11px] font-mono text-[#717669]">
                          {step.index}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Right Column: Hero Workbench (7 cols) */}
          <div className="lg:col-span-7 w-full">
            <ConvexHeroWorkbench />
          </div>
        </div>
      </div>
    </section>
  );
};
